# Base image
FROM osrf/ros:humble-desktop-full

# Set environment variables to avoid some interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update and install base dependencies
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    wget \
    nano \
    python3 \
    python3-pip \
    git \
    cmake \
    curl lsb-release gnupg \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && \
    apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*



# =======================================================================
#                  Installation of Clearpath Simulator
# =======================================================================

# Install Gazebo Fortress
RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt-get update && \
    apt-get install -y ignition-fortress && \
    rm -rf /var/lib/apt/lists/*

# Install Clearpath
RUN apt-get update && \
    apt-get install -y ros-humble-clearpath-desktop \
    && rm -rf /var/lib/apt/lists/*

# Installing Clearpath Simulator
WORKDIR /root/clearpath_ws
RUN mkdir -p src && \
    wget https://raw.githubusercontent.com/clearpathrobotics/clearpath_simulator/humble/dependencies.repos && \
    vcs import src < dependencies.repos && \
    /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install"
WORKDIR /


# Install Clearpath Simulator
RUN apt-get clean && apt-get update && apt-get install -y ros-humble-clearpath-simulator && \
    rm -rf /var/lib/apt/lists/*

# Also Install Various Worlds
WORKDIR /opt/ros/humble/share/clearpath_gz/worlds/
RUN curl -o orchard.sdf https://raw.githubusercontent.com/clearpathrobotics/clearpath_simulator/jazzy/clearpath_gz/worlds/orchard.sdf && \
    curl -o office.sdf https://raw.githubusercontent.com/clearpathrobotics/clearpath_simulator/jazzy/clearpath_gz/worlds/office.sdf && \
    curl -o pipeline.sdf https://raw.githubusercontent.com/clearpathrobotics/clearpath_simulator/jazzy/clearpath_gz/worlds/pipeline.sdf && \
    curl -o construction.sdf https://raw.githubusercontent.com/clearpathrobotics/clearpath_simulator/jazzy/clearpath_gz/worlds/construction.sdf 
WORKDIR /



##### For teleoperation (robot controller), we need additional libraries
RUN apt-get clean && apt-get update && apt-get install -y ros-humble-teleop-twist-keyboard && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir ~/clearpath/

# Install tmux and terminator
RUN apt-get update && apt-get install -y  tmux terminator && apt-get clean


# =======================================================================
#                     Installation of joy2twist
# This library enable us to control the vehicle using joystick. Enjoy it
# =======================================================================
WORKDIR /root/joystick/src
RUN git clone https://github.com/HaktanM/joy2twist.git
WORKDIR /root/joystick
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install"
WORKDIR /

##### In case you want to control with keyboard, this is required
RUN apt-get clean && apt-get update && apt-get install -y ros-humble-teleop-twist-keyboard && \
    rm -rf /var/lib/apt/lists/*


# =======================================================================
#          Installation of FAST LIO and its Dependancies
# =======================================================================

# Install PCL and Eigen
RUN apt-get update && \
    apt install -y libpcl-dev libeigen3-dev

# Upgrade just in case
RUN apt-get update && \
    apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

ARG A_DUMMY_VARIABLE=default_value
# We need a slightly modified version of FastLIO
WORKDIR /root/fast_lio/src
RUN git clone  https://github.com/HaktanM/fast_lio.git
WORKDIR /root/fast_lio/src/fast_lio
RUN git submodule update --init
WORKDIR /root/fast_lio
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install"
WORKDIR /